<div class="subnav">
    <div class="row">
    <ul>
        <a href="/docs/afpg/">
            <li class="small-6 medium-2 columns">
                Training
            </li>
        </a>
        <a href="/mods/?nodownload">
            <li class="small-6 medium-3 columns">
                Scarlet
            </li>
        </a>
        <li class="small-0 medium-2 columns"></li>
        <a href="/faq/">
            <li class="small-6 medium-3 columns">
                FAQ
            </li>
        </a>
        <a href="/media/pack/">
            <li class="small-6 medium-2 columns">
                AAF Media Pack
            </li>
        </a>
    </ul>
    </div>
</div>
