			<footer class="row">
				<figure class="emblum float-left"></figure>
				<a href="http://alexsinnott.me/">
					<figure class="alexsinnott float-right"></figure>
				</a>
				<p>
					Copyright &copy; 2017 Australian Armed Forces | <a href="https://github.com/sifex/AAF-Website">Github</a> | <a href="https://github.com/sifex/AAF-Website/issues/new">Report an Issue</a>
					<span>ARMA 2&trade; ARMA 3&trade; and Bohemia Interactive&trade; are trademarks of Bohemia Interactive.</span>
				</p>
			</footer>
