
	<header>
		<div class="row">
			<nav class="left">
				<a href="/about/">ABOUT</a>
				<a href="/media/">MEDIA</a>
				<a href="/divisions/">DIVISIONS</a>
			</nav>
			<a href="/"><div class="logo"></div></a>
			<nav class="right">
				<a href="/contact/">CONTACT</a>
				<a href="https://discord.gg/0lKWghNku8qNrI6r">DISCORD</a>
				<!-- <a class="button" href="#">APPLY NOW</a> -->
				<a href="/apply/">APPLY</a>
			</nav>
			<a href="#" class="mobile_menu_button"></a>
		</div>
	</header>
