
	<header>
		<div class="row">
			<nav class="left">
				<a href="/about/">ABOUT</a>
				<a href="/media/">MEDIA</a>
				<a href="/divisions/">DIVISIONS</a>
			</nav>
			<a href="/"><div class="logo"></div></a>
			<nav class="right">
				<a href="/contact/">CONTACT</a>
				<a href="//forums.australianarmedforces.org/">FORUMS</a>
				<!-- <a class="button" href="#">APPLY NOW</a> -->
				<a href="https://docs.google.com/forms/d/1Ltyj22AZ9GbehFdYJ_e1Dj8ppr-cQvwP1_gL85axuKg/viewform">APPLY</a>
			</nav>
			<a href="#" class="mobile_menu_button"></a>
		</div>
	</header>
