<aside class="promo-tiles">
	<section>
		<div class="promo-tile promo-1 small-12 medium-6 large-3 columns">
			<a href="/apply/">
				<span class="alt">Apply to Join the Australian Armed Forces</span>
			</a>
		</div>
		<div class="promo-tile promo-2 small-12 medium-6 large-3 columns">
			<a href="https://www.youtube.com/user/AustArmedForces">
				<span class="alt">Youtube Channel</span>
			</a>
		</div>
		<div class="promo-tile promo-4 small-12 medium-6 large-3 columns">
			<a href="/about/">
				<span class="alt">Who are the Australian Armed Forces?</span>
			</a>
		</div>
		<div class="promo-tile promo-3 small-12 medium-6 large-3 columns">
			<a href="https://github.com/aam-mod/AAM">
				<span class="alt">Australian Army Modification</span>
			</a>
		</div>
	</section>
</aside>
