		<script src="/bower_components/jquery/dist/jquery.js"></script>
		<script src="/bower_components/what-input/what-input.js"></script>
		<script src="/bower_components/foundation-sites/dist/foundation.js"></script>
	    <script src="/js/jquery.smoothState.js"></script>
	    <script src="/js/parallax.js"></script>

	    <script>
	    ;(function ($) {
	      $('#content').smoothState();
	    })(jQuery);
	    </script>
	</body>
</html>
