			<footer class="row">
				<figure class="emblum float-left"></figure>
				<figure class="alexsinnott float-right"></figure>
				<p>
					Copyright &copy; 2016 Australian Armed Forces
					<span>ARMA 2&trade; ARMA 3&trade; and Bohemia Interactive&trade; are trademarks of Bohemia Interactive.</span>
				</p>
			</footer>
			</main>
		</div>


		<script src="/bower_components/jquery/dist/jquery.js"></script>
		<script src="/bower_components/what-input/what-input.js"></script>
		<script src="/bower_components/foundation-sites/dist/foundation.js"></script>
	    <script src="/js/jquery.smoothState.js"></script>
	    <script src="/js/parallax.js"></script>

	    <script>
	    ;(function ($) {
	      $('#content').smoothState();
	    })(jQuery);
	    </script>
	</body>
</html>
