<!doctype html>
<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="x-ua-compatible" content="IE=Edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Australian Armed Forces - Arma 3&trade; Unit</title>

		<link rel="stylesheet" href="/global/styles/aaf-global.css" />
		<link rel="stylesheet" href="<!--#echo var='stylesheet' -->" />
	</head>
	<body>
	<header>
		<div class="row">
			<nav class="left">
				<a href="/about/">ABOUT</a>
				<a href="/media/">MEDIA</a>
				<a href="/divisions/">DIVISIONS</a>
			</nav>
			<a href="/"><div class="logo"></div></a>
			<nav class="right">
				<a href="/contact/">CONTACT</a>
				<a href="/forums/">FORUMS</a>
				<!-- <a class="button" href="#">APPLY NOW</a> -->
				<a href="/apply/">APPLY</a>
			</nav>
			<a href="#" class="mobile_menu_button"></a>
		</div>
	</header>